### ISSUE TITLE
High CPU Usage with submaps

### ISSUE THREAD

**Issue by TheMC47** [xmonad/xmonad-contrib#483] opened 2021-03-19 11:20 UTC
### Problem Description

There's a high CPU Usage when using submaps. Probably we're doing some kind of active waiting? I'm not familiar with the code. 

### Steps to Reproduce

Use the configuration file provided below, and monitor the CPU usage (I used xmobar's CPU monitor). Press `M-a` and wait a bit. The numbers should fly-off (I had 98% usage). Pressing `t` will then free the CPU.

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
module Main (main) where

import XMonad
import XMonad.Util.EZConfig

myTerminal = "termite"

main :: IO ()
main = xmonad def `additionalKeysP` [ ("M-a t", spawn myTerminal)]
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by slotThe** [comment] 2021-03-19 12:23
How long is "a bit"?  I let it run for a few minutes, but couldn't notice any CPU increase.  We have other issues in this direction (#327 and #262) so it's probably real, but I can't reproduce this with the given minimal config.

**Comment by TheMC47** [comment] 2021-03-19 12:35
A bit is a couple of seconds. I didn't test that particular config, but I thought it would cause the behavior. Any suggestions for how to monitor the CPU, so I can provide a real config that reproduces this problem?

**Comment by geekosaur** [comment] 2021-03-19 12:38
There are CPU monitors in most status bars including xmobar.

**Comment by slotThe** [comment] 2021-03-19 12:38
> Any suggestions for how to monitor the CPU, so I can provide a real config that reproduces this problem?

I just had `htop` open when testing this, especially when we're talking about 100% usage that or something similar should be more than enough

**Comment by TheMC47** [comment] 2021-03-19 12:55
I removed everything else from my config, and the issue is there

**Comment by geekosaur** [comment] 2021-03-19 13:27
We're doing `getEvent` aka `XNextEvent()`, not busylooping.

**Comment by liskin** [comment] 2021-03-19 13:29
Might be a good idea to put `io $ print ev` after that `getEvent` and see what comes out of it.

**Comment by TheMC47** [comment] 2021-03-19 14:36
It's printing:
```
KeyEvent {ev_event_type = 2, ev_serial = 1562, ev_send_event = False, ev_event_display = Display 0x0000000000d92d10, ev_window = 600, ev_root = 600, ev_subwindow = 96468995, ev_time = 21527023, ev_x = 2510, ev_y = 547, ev_x_root = 2510, ev_y_root = 547, ev_state = 0, ev_keycode = 36, ev_same_screen = True}
``` 
once

**Comment by geekosaur** [comment] 2021-03-19 14:45
Can you use htop to see if it's xmonad or some other app that's spinning?

**Comment by TheMC47** [comment] 2021-03-19 14:58
htop says it's xmonad

**Comment by geekosaur** [comment] 2021-03-21 15:00
Also appears to possibly be a duplicate of #262.

**Comment by TheMC47** [comment] 2021-04-07 11:01
I experienced this issue with the prompt as well: I open a prompt, and wait. The CPU Usage goes up; and after pressing a key, it goes down again; only to go up just after that

**Comment by TheMC47** [comment] 2021-04-07 11:01
I experienced this issue with the prompt as well: I open a prompt, and wait. The CPU Usage goes up; and after pressing a key, it goes down again; only to go up just after that

**Comment by TheMC47** [comment] 2021-04-07 11:04
Maybe this is an X11 issue? I'm building it with the https://github.com/xmonad/X11/commit/6285080d6c0f0369ba729f45d636efd18182bb30

**Comment by slotThe** [comment] 2021-04-07 11:43
On Wed, Apr 07 2021 04:04, Yecine Megdiche wrote:
> Maybe this is an X11 issue? I'm building it with the
> https://github.com/xmonad/X11/commit/6285080d6c0f0369ba729f45d636efd18182bb30

I just rebuild everything with this commit, but I still can't reproduce
the issue :/

**Comment by liskin** [comment] 2021-04-07 17:29
Maybe it's time for us to start comparing GHC versions and rtsflags? :-)

@TheMC47 If you can reproduce it reliably, then it'd be best to ssh from another machine and check what's using the CPU. But I think you already mentioned it was xmonad indeed, so the next step would be to strace it and perhaps even try attaching gdb and check if it's looping in Xlib or in RTS or in actual xmonad code. If you don't have another machine then the next best thing is to try reproducing in Xephyr.

**Comment by TheMC47** [comment] 2021-04-07 21:15
I'm using `lts-17.8` as my resolver, and I'm building with `-threaded -rtsopts -with-rtsopts=-N -Wall`. These are the relevant files https://github.com/TheMC47/dotfiles/blob/master/xmonad/.xmonad/xmonad-private.cabal and https://github.com/TheMC47/dotfiles/blob/master/xmonad/.xmonad/stack.yaml .

@liskin  I don't have a second machine, so I'll try Xephyr. I won't be able to do that any time soon (e.g. in the next week) though :/

**Comment by slotThe** [comment] 2021-04-10 13:13
> -threaded -rtsopts -with-rtsopts=-N -Wall

Ah indeed, that seems to be the cause; I can reproduce this if I compile with the threaded runtime.

**Comment by TheMC47** [comment] 2021-05-01 13:27
Removing the flags does fix the problem. So should we still consider this an issue? Could we do something about it?

**Comment by liskin** [comment] 2021-05-01 13:30
I'm still curious what the issue really is but I won't get to it very soon.

**Comment by liskin** [comment] 2021-08-09 00:15
It was the parallel GC in combination with `XMaskEvent` being foreign imported "unsafe".
Fix here: https://github.com/xmonad/X11/pull/78

**Closed** 2021-08-15 14:25 UTC
Labels: 0.kind: bug, 9.needs: reproducible via config
