### ISSUE TITLE
XMonad-Contrib Documentation Updates

### ISSUE THREAD

**Issue by davama** [xmonad/xmonad-contrib#83] opened 2016-09-14 18:19 UTC
Hello, 
Here's a radical/crazy idea: (im sure this has been addressed before but couldnt find where)

The idea is moving the xmonad-contrib documentation, [link](http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Doc.html), to GIT as a wiki. I know it sounds crazy but just want to make a pitch.

I've forked this repo and played with it. Added a [Documentation](https://github.com/davama/xmonad-contrib/blob/master/README.md) section to the README.md file. 
Please take a look.

I'm perfectly fine being shutdown because of the mountain of work/updates this will create. It's not a turnkey solution but it's a start i think.

**Note:** I am not a haskell developer but i enjoy xmonad very much.
### What i did:
1. cloned myfork
2. copied html doc files (~/.cabal/html/) to local fork under "Documentation" folder
3. created Documentation_testing folder and copied html files from previous Doc folder
4. change ".html" string to ".md" on all html files 
5. converted all html files to md file using `pandoc`
6. At this point i removed lines that didnt look nice. (MHO of course)
7. Push to myfork
### Command rundown of what i did: (starting at # 4)

```
cd ~/xmonad-docfork/xmonad-contrib/Documentation_testing/
for i in $(ls *.html); do sed -i 's/.html/.md/g' $i; done
for i in $(ls *.html); do name=$(echo $i | sed 's/.html//g'); pandoc -f html -t markdown_mmd $name.html > $name.md; done
rm *.html
```

At this point im removing things that are not pleasing to my eyes. ( # 6 ) (some lines created by `pandoc` )

```
for i in $(ls *.md); do sed -i '/xmlns=/d' $i ; done
for i in $(ls *.md); do sed -i '/\[Index\]/d' $i; done
for i in $(ls *.md); do sed -i '/\[Contents\]/d' $i; done
for i in $(ls *.md); do sed -i 's/\[g:.\]//g' $i; done
for i in $(ls *.md); do sed -i '/&lt;.md&gt;/d' $i; done
for i in $(ls *.md); do sed -i '/xmonad-contrib-0.12: Third/d' $i; done
for i in $(ls *.md); do sed -i '/|              |                          |/d' $i; done
for i in $(ls *.md); do sed -i '/| Copyright/d' $i; done
for i in $(ls *.md); do sed -i '/| License/d' $i; done
for i in $(ls *.md); do sed -i '/| Maintainer/d' $i; done
for i in $(ls *.md); do sed -i '/| Stability/d' $i; done
for i in $(ls *.md); do sed -i '/| Portability/d' $i; done
for i in $(ls *.md); do sed -i '/| Safe Haskell/d' $i; done
for i in $(ls *.md); do sed -i '/| Language/d' $i; done
for i in $(ls *.md); do sed -i '/|-------------/d' $i; done
for i in $(ls *.md); do sed -i '/^| *| *|$/d' $i; done
```

Let me know what you guys think.

-Dave

**Comment by f1u77y** [comment] 2016-09-14 21:15
What are the reasons behind *moving* documentation? Actual docs for 0.12 are on hackage, so the only reason to have them on github is to have actual docs for git version. But I think anyone who uses git version should generate docs himself if he wants to use them because he can make his own changes or his version might be outdated compared to master.

**Comment by davama** [comment] 2016-09-15 18:16
> What are the reasons behind moving documentation?

My understanding was that they are not up to date. I could be wrong.

> Actual docs for 0.12 are on hackage

Is that [here](http://xmonad.org/documentation.html)?

I know there has been changes to the way modules run in the past, i dont know all the changes but i do remember one in particular, [X.A.UpdatePointer](http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Actions-UpdatePointer.html)
The doc has `logHook = updatePointer (Relative 0.5 0.5)` but that is no longer valid. (This is just to show that it's not current, im sure there's other ones)

Also all those docs say "xmonad-contrib-**0.11**: Third party extensions for xmonad" at the very top. And [haskell-xmonad](http://hackage.haskell.org/package/xmonad) is on V0.12. (aesthetic issue but docs dont reflect version of code)

.....

Now that i think about it and search a little i see the haskell docs you talking about. (~/.cabal/html/XMonad-UpdatePointer.html  etc) yes, those looks like they are up to date. ( i only checked UpdatePointer since that's the discrepancy i know)

That being said then the question is, are these haskell docs publish anywhere on the web? and/or will the xmonad.org docs be updated?

Another reason why i thought of having them on git was to keep track of changes on the master and simply import them to the "public" haskell/xmonad documentation when ever it's decided to bump the version number to 0.13. (of course im not familiar with the whole "change management process" you follow so this could be irrelevant)

Thanks

**Comment by f1u77y** [comment] 2016-09-15 18:24
> Is that here?

No, hackage is [here](https://hackage.haskell.org/)

> My understanding was that they are not up to date. 

They are not up to date only at xmonad.org but hackage has up to date version.

> Also all those docs say "xmonad-contrib-0.11: Third party extensions for xmonad" at the very top. 

(Here)[http://hackage.haskell.org/package/xmonad] you can find section "Modules". There are docs for 0.12 here.

> simply import them to the "public" haskell/xmonad documentation when ever it's decided to bump the version number to 0.1

The docs will be upliaded on Hackage with next release without your changes, what's the problem?

**Comment by davama** [comment] 2016-09-15 19:06
Thanks for providing the link to the hackage docs. 

> The docs will be upliaded on Hackage with next release without your changes, what's the problem?

I guess the issue now is that xmonad.org docs are not up to date. Granted yes, they exist and updated in hackage but someone new, **wanting to try xmonad**, wouldn't find the latest docs that easy. (a simple google search of "xmonad" results with xmonad.org link) 

In my case for example, when i decided to try xmonad, in 2013, xmonad was still on V0.11 so those docs were very helpful, and i still refer to them. (now i know where to find the updated ones, so that helps) Now we are on V0.12 and any unsuspecting person could easily be directed to xmonad.org and find V0.11 docs.

Again im just an end-user, im not privy to all the ins-and-outs with xmonad changes but if life could get easier when playing/learning xmonad, why not.

Thank you for the support

**Comment by f1u77y** [comment] 2016-09-15 20:28
> someone new, wanting to try xmonad, wouldn't find the latest docs that easy

So the issue is just about outdated docs on xmonad.org. My opinion is thare is no reason to keep compiled docs in more than one place, so I think docs should be removed from xmonad.org(and docs page probably should point to hackage instead)

**Comment by twifkak** [comment] 2016-09-15 20:45
Ideally, the existing xmonad.org URLs would redirect to their corresponding
URLs on hackage. It looks like this is possible using 404.html and a bit of
Liquid scripting. See
http://yizeng.me/2013/05/26/create-a-custom-jekyll-404-page/ for instance.

**Comment by twifkak** [comment] 2016-09-15 20:46
Oh, and the xmonad-web repo is here: https://github.com/xmonad/xmonad-web

**Comment by f1u77y** [comment] 2016-09-15 20:56
@twifkak it can be even more simple: just change links from in http://xmonad.org/documentation.html and remove unused pages with outdated docs

**Comment by twifkak** [comment] 2016-09-15 21:11
True, but a bunch of these things are already linked to on the web.
Unfortunately, Google got rid of the link: operator, but you can at least
see the pages where people mention the URL in plaintext:
https://www.google.com/search?q=
"http%3A%2F%2Fxmonad.org%2Fxmonad-docs%2F"+-inurl%3A"http%3A%2F%2Fxmonad.org%2Fxmonad-docs%2F"

I don't have commit access to xmonad-web, so my opinion is not
authoritative, but IMO it'd be nice to avoid breaking links if it's not too
painful. (e.g. a meta refresh tag on each of the pages could be simpler to
implement, though harder to maintain).

**Comment by chrissound** [comment] 2016-10-19 21:12
What is the status of this task? 

Regarding existing links, redirecting them sounds like a plan. Perhaps we just need to compile a list of redirect mappings?

**Comment by pjones** [comment] 2017-04-10 20:46
I'm closing this in favor of xmonad/xmonad#94 and #154.

**Closed by pjones** 2017-04-10 20:46 UTC
