### ISSUE TITLE
Submap breaks with xdotool and taxing configuration

### ISSUE THREAD

**Issue by Radvendii** [xmonad/xmonad-contrib#327] opened 2019-11-25 17:09 UTC
### Problem Description

When I'm using a sufficiently taxing* configuration file, and I have `xdotool click --clearmodifiers 1` after a submap, it never triggers.

*I'm not sure exactly what qualifies, but there are a few things that seem to trigger this bug: a lot of workspaces, a super complex layout hook, and nesting submaps (maybe related to #262)

This originally came up because i had a recursive submap that allowed me to move the mouse and then click, but it didn't work if I moved the mouse too many times before clicking.

### Configuration File

Please include the smallest configuration file that reproduces the
problem you are experiencing:

```haskell
import XMonad
import XMonad.Core
import XMonad.Actions.Submap
import qualified Data.Map as M

myWorkspaces = map show [1..5000]

myModMask = mod4Mask

myKeys _ = M.fromList $
  pure ((myModMask, xK_space),
         submap . M.fromList $ [ ((0, xK_space), (spawn "xdotool click --clearmodifiers 1")) ])

main = xmonad $ defaultConfig {
    modMask    = myModMask,
    workspaces = myWorkspaces,
    keys       = myKeys
  }

```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by geekosaur** [comment] 2019-11-25 21:37
You're going to have to use `XMonad.Util.Ungrab` for that kind of thing to work reliably; the grab is held through execution of the command because xmonad has no way of knowing whether the action is another submap or etc. that needs a continuous grab to work, and if the command executes quickly enough the grab will still be held and the click will be lost. See the documentation for `unGrab` for more details.

**Comment by Radvendii** [comment] 2019-11-26 00:27
That's a good thought. `unGrab` doesn't solve this problem, though.* That was one of the first things I tried. Also, if you look at the code for submap, it has this code there:
https://github.com/xmonad/xmonad-contrib/blob/52f8c82504e24fb78380819ddffb0ec19b56a763/XMonad/Actions/Submap.hs#L94-L95

which is exactly how `unGrab` is implemented:
https://github.com/xmonad/xmonad-contrib/blob/52f8c82504e24fb78380819ddffb0ec19b56a763/XMonad/Util/Ungrab.hs#L42-L43

*Caveat: IIRC, `unGrab` did *help*, by which I mean that when I put it in there, it required more iterations of submap (which was how I was getting this bug to happen at the time) in order to trigger the bug.

**Comment by geekosaur** [comment] 2019-11-27 16:37
This sounds like something is still holding or re-acquiring the grab despite both ungrabs, then. (And I'm a bit surprised at the implementation, since it means Submap can't be used with some other kind of e.g. menu implementation, or with Prompt, etc., because the early ungrab means the action can't itself use mouse or key events.)

**Comment by Radvendii** [comment] 2019-11-27 16:58
Why would this be triggered by too many workspaces / too complex a configuration? Is the grab somehow not happening because the CPU is too taxed or something? How would I test your hypothesis that things aren't getting `unGrab`ed?

**Comment by Radvendii** [comment] 2019-11-27 19:58
> the early ungrab means the action can't itself use mouse or key events.

I didn't look at this code in as much detail, but it seems like maybe prompt performs its own grab?

https://github.com/xmonad/xmonad-contrib/blob/52f8c82504e24fb78380819ddffb0ec19b56a763/XMonad/Prompt.hs#L595

**Comment by geekosaur** [comment] 2019-11-27 21:33
It may but probably shouldn't; that's a way to invite events to be lost.

What do you expect to receive the mouse click? If you're doing these in quick succession, it may be being delivered to the Submap instead of to a window (both are held during the normal grab).

**Comment by Radvendii** [comment] 2019-11-27 21:47
> What do you expect to receive the mouse click? 
Various things. Mostly I've been testing on neovim (which can normally receive clicks fine), or just using it to switch window focus.

> If you're doing these in quick succession, 
Doing what in quick succession? I've tried pressing keys at various tempos and it all has the same result.
 
> it may be being delivered to the Submap instead of to a window (both are held during the normal grab).
Both what are held? The window and the Submap? Held by what? I'm confused.

Thanks for your patience, I'm not very familiar with X programming.

**Comment by geekosaur** [comment] 2019-11-28 15:32
I'm still trying to understand the circumstances of the failure.

There are two grabs (== locks) held (X11 has 3): mouse and keyboard events. (There's also grabbing the whole server; this is used to freeze the screen for e.g. screenshots.) This can mean that mouse events from outside go to the wrong place, if you are expecting only the keyboard to be grabbed by a Submap. I spoke a bit imprecisely earlier, since xmonad treats the two grabs as one in effect, it can't tell whether a keyboard or mouse grab triggered the Submap as it was acquired passively in response to either a keyboard or mouse action.

**Comment by Radvendii** [comment] 2019-12-02 16:56
Yes, I understand that submap will grab both keyboard and mouse.

What other information / testing would be helpful?

**Comment by slotThe** [comment] 2021-07-26 07:02
I'm going to close this as a duplicate of #483, as that issue has more information on how to reproduce this behaviour

**Closed by slotThe** 2021-07-26 07:02 UTC

**Comment by liskin** [comment] 2021-08-08 22:41
This may actually need https://github.com/xmonad/xmonad-contrib/pull/586, which would explain why this also happened with complex configurations: it'd take longer for xmonad to get back to the main loop which flushes Xlib queue.
