### ISSUE TITLE
Leakage of swallowed windows when X.H.WindowSwallowing used with X.L.TrackFloating + X.H.EwmhDesktops.ewmhFullScreen 

### ISSUE THREAD

**Issue by PRESFIL** [xmonad/xmonad-contrib#416] opened 2020-12-03 21:26 UTC
### Problem Description

If you run the `mpv video_file` in the terminal and the terminal is swallowed by `mpv` + `mpv` will expand to full screen with **EWMH**, the terminal will not be restored after `mpv` is finished.

It is also somehow affected by `X.H.DynamicLog` (possibly due to *struts*).

### Configuration File (minimized)

```haskell
import XMonad
import XMonad.Hooks.DynamicLog
import XMonad.Hooks.EwmhDesktops
import XMonad.Hooks.WindowSwallowing
import XMonad.Layout.TrackFloating

myLayouts = trackFloating $ layoutHook def

mySwallowHook = swallowEventHook ( className =? "Alacritty" <||> className =? "Termite" ) ( return True )

main = do
  xmonad =<< xmobar (ewmhFullscreen (ewmh def
    { modMask = mod4Mask
    , layoutHook = myLayouts
    , handleEventHook = mySwallowHook <+> ewmhDesktopsEventHook <+> handleEventHook def
    }))
```

My current terminal is `alacritty`. On `termite` issue also reproducible.
[xmonad](https://aur.archlinux.org/packages/xmonad-git/) version: `v0.15.r25.g5be975b-1`
[xmonad-contrib](https://aur.archlinux.org/packages/xmonad-contrib-git/) version: `v0.16.r197.g6381a468-1`

I'm using fresh `-git` version of packages.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by liskin** [comment] 2020-12-14 01:06
@elkowar can you please take a look at this one? Thanks.

**Comment by elkowar** [comment] 2020-12-14 01:08
Sure, I'll take a look!

**Comment by PRESFIL** [comment] 2020-12-14 16:25
Thanks! I'm experiencing this behavior not only with `mpv`, if it's important.

I will wait very carefully.

**Comment by PRESFIL** [comment] 2021-01-01 14:13
I think I confused `mpv` with `ffplay`. Externally, they are both like a window without buttons :sweat_smile: .
To play it, you need to allow the video to be played to the end.

**Comment by PRESFIL** [comment] 2021-01-17 07:07
This also happens sometimes with `mpv'.

**Comment by slotThe** [comment] 2021-01-27 17:51
@PRESFIL I can't reproduce this; could you perhaps add some more steps
on how you get this behaviour?
  
  ### What I did
  
  1. I used the following config (essentially yours, just with some
     stuff removed)
  
       ``` haskell
       import XMonad
       import XMonad.Hooks.DynamicLog
       import XMonad.Hooks.EwmhDesktops
       import XMonad.Hooks.WindowSwallowing
       import XMonad.Layout.TrackFloating
       
       main = xmonad
            . ewmhFullscreen
            . ewmh
          =<< xmobar def
                { layoutHook      = trackFloating (layoutHook def)
                , handleEventHook = mconcat
                    [ ewmhDesktopsEventHook
                    , swallowEventHook (className =? "Alacritty") (return True)
                    , handleEventHook def
                    ]
                }
       ```
  
  2. I spawned some `alacritty` instances
  
  3. I executed 
  
       ``` shell
       ffplay -fs -autoexit SOME-VIDEO
       ```
  
     in one of the terminals.  The video at this point began to play
     normally (full screen).
  
  4. Once the video was done playing, I was correctly send back to the
     terminal.  One thing I noticed was that the terminal was now also
     fullscreen, so it had to be pushed back into tiling with `M-t`
     (which certainly felt a bit annoying, though that's not the issue
     we're discussing here).
     
I also tried the same procedure with `mpv`, but that one behaved
correctly as well.

**Comment by PRESFIL** [comment] 2021-01-28 06:06
1. I think what you deleted was important after all. Try the config that is located at the beginning of the topic.
2. I also noticed that this only happens when the file is run from `vifm`. To make sure I manually select the player, `ffplay -fs -autoexit SOME-VIDEO`.

**Comment by slotThe** [comment] 2021-01-28 08:38
>     1. I think what you deleted was important after all. Try the config that is located at the beginning of the topic.

Did that, nothing changed.

>     2. I also noticed that this only happens when the file is run from `vifm`. To make sure I manually select the player, `ffplay -fs -autoexit SOME-VIDEO`.

It is really hard for someone unfamiliar with these program to know _exactly_ what you did; this is why I explicitly asked you for a detailed step-by-step guide on how to reproduce this (for dummies, like me :) 

#### What I did this time

1. I used the config given in the OP verbatim
2. I spawned some `alacritty` instances
3. I executed `vifm --on-choose "ffplay -fs -autoexit %c"` in one of them
4. I selected some video 
5. Once the video was finished, I was send back to the terminal (`vifm` had exited at this point; I'm not sure that is expected behaviour, but it's also not the issue we're talking about)
6. As above, the terminal was now floating an fullscreen, but it was there

**Comment by PRESFIL** [comment] 2021-01-28 08:59
I repeated your last actions and the window disappears.
I don't know what else could be the difference. 

Maybe I can provide some kind of log? In `~/.xsession-errors` mix of errors from many programs, maybe there is another way?

**Comment by slotThe** [comment] 2021-01-28 09:11
Could it perhaps be your `alacritty` config?  I was testing this with the default one (I also don't have any configs for `ffplay` and `vifm`).  

I can't help you much in debugging if I can't reproduce the issue.  I suppose the best you can do is litter the module with traces (`Debug.Trace.trace`, for example) and see what exactly happens after the video exits and the terminals vanishes vs. something else exits and the terminal is restored.

**Comment by liskin** [comment] 2021-02-11 11:59
@elkowar It just occurred to me that WindowSwallowing could be implemented more reliably on top of SubLayouts, by tabbing the windows together instead of swallowing. It'd obviously only be usable for users who have a subtabbed layout using SubLayouts, but it'd provide an enhanced experience, where they could still access the parent window if necessary, and there's no risk of a window leaking.

The implementation should also be simpler, although I'm not sure how one can merge SubLayouts groups from a ManageHook. That needs to be done after the window is managed, but we don't have any `X` hook that runs after. I'm afraid I might need some logHook for delayed execution of stuff. :-/

Anyway, it's just an idea that might be implemented separately from this X.H.WindowSwallowing.

**Comment by elkowar** [comment] 2021-02-11 12:24
@liskin sounds like a great idea! Yea, itd only be usable for people with tab stuff, which isnt possible in all layouts (i.e. the mouseResizable stuff), so it should definitely be separate. The detection part of my implementation could be reused though

**Comment by PRESFIL** [comment] 2021-02-11 21:27
@liskin , heh, I previously used tabs as a replacement for swallow on `i3wm`. And yes - I would really like to be able to **unswallow** something - for debugging. I haven't tried the tabbed solution yet.

**Comment by liskin** [comment] 2021-02-11 21:29
@PRESFIL There isn't any tabbed swallowing yet to try, but I'll try to come up with something later.

**Comment by PRESFIL** [comment] 2021-02-11 21:33
I mean, I haven't yet taught myself **tabbed sublayout** and used it as a substitute for *swallowing*. I used this method earlier in `i3wm`.

**Comment by slotThe** [comment] 2021-12-13 16:43
Closing since that functionality is implemented now (and no repro on the original report :()

**Closed by slotThe** 2021-12-13 16:43 UTC

**Comment by PRESFIL** [comment] 2021-12-13 18:17
Yes, I also thought I should have closed this issue a couple of days ago.
After reinstalling system and updating to `0.17` did not try to reproduce this bug.
