### ISSUE TITLE
Modify X.U.ClickableWorkspaces to work with X.A.DynamicWorkspaces

### ISSUE THREAD

**Issue by oogeek** [xmonad/xmonad-contrib#510] opened 2021-04-12 06:26 UTC
### Problem Description

I am wondering if it is necessary or useful to modify `X.U.ClickableWorkspaces` to work with `X.A.DynamicWorkspaces`.
For single monitor, I think the change is quite simple. I would be happy to open a PR if it is considered useful.

After some reading, the only limitation here comes from `getWsIndex`. 
```
-- | Lookup the index of a workspace id in the user's config, return Nothing
-- if that workspace does not exist in the config.
getWsIndex :: X (WorkspaceId -> Maybe Int)
getWsIndex = do
    spaces <- asks (workspaces . config)
    return $ flip elemIndex spaces
```
It only uses predefined workspaces.
I think for single monitor, a minor change would be good enough.

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by oogeek** [comment] 2021-04-12 06:34
I find out that `getSortByIndex` from `X.U.WorkspaceCompare` do address the issue. However, the issue exists in `X.U.ClickableWorkspaces`

**Comment by liskin** [comment] 2021-04-12 10:25
Can you elaborate how exactly did you solve the issue using `getSortByIndex`? I have a rough idea what the problem is but if you have a working fix for `ClickableWorkspaces` that would be marvellous.

(I don't think I'll have time to fix this myself this week.)

**Comment by oogeek** [comment] 2021-04-12 15:28
So when the newly added workspace is passed to `getWsIndex`, it will return a `Nothing`. `getSortByIndex` manages this by using compare functions. So import a `getSortByIndex` will be helpful here.

**Comment by slotThe** [comment] 2021-04-15 06:44
Closed via #512

**Closed by slotThe** 2021-04-15 06:44 UTC
