### ISSUE TITLE
X.L.NoBorders flashes border when switching workspaces

### ISSUE THREAD

**Issue by sporkm** [xmonad/xmonad-contrib#316] opened 2019-10-02 05:23 UTC
### Problem Description

Whenever I switch from one workspace to another, if the workspace I'm switching from is using a layout modified with `noBorders`, there will be a border flash (reverting to the border width set through XConfig) for a fraction of a second before it switches to the other workspace and applies its layout.

This happens even if I'm not using a compositor like compton with fading effects.

Expected behavior: no border flash, simply switch to the new layout and apply it.

### Configuration File

```haskell
module Main (main) where

import XMonad
import XMonad.Layout.NoBorders

main :: IO ()
main = xmonad $ def
        { borderWidth = 2
        , workspaces = ["one", "two"]
        , layoutHook = noBorders Full
        }
```

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

**Comment by apvodney** [comment] 2020-05-08 04:05
This happens to me as well, but when alt-tabbing between windows in the Full layout with noBorders.

**Comment by slotThe** [comment] 2021-11-13 08:12
I believe this is fixed by [X.L.VoidBorders](https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Layout-VoidBorders.html), so closing this for now

**Closed by slotThe** 2021-11-13 08:12 UTC

**Comment by d3adb5** [comment] 2021-11-25 11:50
> I believe this is fixed by [X.L.VoidBorders](https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Layout-VoidBorders.html), so closing this for now

Not quite. X.L.VoidBorders will completely disable borders on whatever window happens to go into a layout it modifies. I made it that way because the windows I would normally put in a workspace using a layout without borders will normally be kept there forever.

If you use, say, `voidBorders Full ||| Full` for your layout hook, any window you display using the first layout there will have no borders for the rest of its lifetime, even if you switch to a normal `Full` layout. Only a screen refresh (or a call to `setWindowBorderWidth`) will restore that window's borders. `voidBorders` doesn't take it upon itself to restore borders when a window "leaves" the layout, and XMonad isn't setting initial properties every time a layout is changed, which is a good thing.

I think this issue can be reopened, if there aren't any duplicates or similar issues still open.

**Comment by viriuwu** [comment] 2022-02-21 09:37
Happening to me as well on version 0.17, and yeah it's not fixed by [X.L.VoidBorders](https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Layout-VoidBorders.html), that just permanently removes it. I don't see a duplicate, so this should probably be reopened?

**Comment by liskin** [comment] 2022-02-21 10:08
VoidBorders recently (<https://github.com/xmonad/xmonad-contrib/pull/682>) gained the ability to restore borders as well, so your example becomes `voidBorders Full ||| normalBorders Full` and should work. It's still a bit cumbersome, but I'm afraid the flashing with `noBorders`/`smartBorders` is by design and can't easily be fixed.
