### ISSUE TITLE
XMonad.Config.Prime and RebindableSyntax

### ISSUE THREAD

**Issue by lierdakil** [xmonad/xmonad-contrib#54] opened 2016-04-29 09:25 UTC
Okay, so I don't really get it. Why isn't `Prime` a `Monad`? From what I can tell, `Prime` is basically a (partially applied) function `XConfig -> XConfig`. While `>>` composition rules for function monad discard left operand entirely, it's possible to reformulate this problem in terms of state monad with `XConfig` being a state, and monadic actions in `Prime` acting upon said state. I don't think there's a huge difference performance-wise.

So, why the whole RebindableSyntax thing? It just makes working with actual monads (like IO) awkward.

**Comment by twifkak** [comment] 2016-04-30 00:17
Prime is a function from XConfig l1 -> XConfig l2, and state monad doesn't
allow for the type of the state to change.

It does make working with actual monads awkward. If you're doing a lot of
that, recall that you can stick other .hs files in your .xmonad and don't
need to enable RebindableSyntax for them.

That said, I'd love a version of (>>=) that works on both Prime and Monad.
I tried a bunch myself and couldn't get the compiler to like me. I
eventually asked a mailing list and got one potential solution on this, but
never took the time to try it out after that. Honestly, you're the first
person who's claimed to look at X.C.Prime; I thought I was the only user,
and it didn't bother me so much.

If there are a few +1s on this bug, I'll give it another go in the next
couple weeks. In the meantime, patches welcome.

**Comment by geekosaur** [comment] 2016-04-30 00:24
I'm thinking you may want to wait for ApplicativeDo to land in ghc8. You don't actually want Monad here, but Applicative.

**Comment by lierdakil** [comment] 2016-04-30 21:17
I'm pretty sure applicative do won't help here, since it mostly works with cases like `f <$> arg1 <*> arg2 ... `, while what we want for `Prime` is more like `expr1 >=> expr2 >=> ...`, (due to it actually being `XConfig l → IO (XConfig l')`). I think `<$>` might work as well, but I couldn't make it work in my head with applicative do syntax (note that arrow notation doesn't work here either)

I've dug around a bit, and it's possible that indexed monads could be an answer (since regular monads are a subset). Couldn't make it work yet though, and I don't think it will be satisfactory (due to need to 'lift' regular monads into indexed monads for syntax to work for those).

Another option could be to build a config transformation AST and *then* apply it, so that AST building could be encapsulated into state monad. I think something like this was attempted in https://github.com/xmonad/xmonad-contrib/blob/master/XMonad/Config/Monad.hs, but that seems to have died off 7 years ago.

@twifkak, what was that potential solution that you got from mailing list? I might poke around to see if it's viable.

**Comment by lierdakil** [comment] 2016-05-01 06:22
Huh. Using `Layout` existential type to wrap every layout type seems to work well enough.

That boils down to

```haskell
type Prime = Arr (XConfig Layout)
type Arr x = StateT x IO ()
```
and a bogus instance

```haskell
instance Read a => Read (Layout a) where
    readsPrec _ = const []
````

Only problem is, I don't think it's possible to construct a proper `Read` instance for an existential type -- unless you want to maintain a list of everything that could be inside. So layout persistence on config reload is lost (possibly something else as well)

**Comment by geekosaur** [comment] 2016-05-01 06:29
Yes. I actually thought of that first, but the Read instance is already the source of a number of issues --- and is why the "public" XConfig is unwrapped, the wrapping only happening when it is converted to an XConf for internal use.

**Comment by aavogt** [comment] 2016-05-01 21:21
@lierdakil When all you have is a `Layout a`, you can still use a function like
the following (which is pretty much what XMonad has in Main.hs):

      lread :: Layout a -> String -> Maybe (Layout a)
      lread (Layout a) s = Layout <$> (readMaybe s `asTypeOf` Just a)

That code ends up using the Read dictionary hidden in the first argument,
trying it and giving Nothing if it can't be read (XMonad ends up using
the supplied (Layout a) in that case, but I don't think that's important
for your problem)

I thought the situation with layout modifiers was the problem: I think when
I wrote
<https://github.com/xmonad/xmonad-extras/blob/master/XMonad/Config/Alt.hs
XMonad.Config.Alt in xmonad-extras>, I kept the `l` type parameters in the
open (no existentials).  I didn't know how to express the idea that `m l a` is
a layout provided that `l a` is also a layout, without having being able to
mention the `l`. IE. I thought you couldn't write a
function `wrap` such that `(wrap Mirror) :: Layout a -> Layout a`.

<https://gist.github.com/aavogt/6105a670be8dd0c48649118c8f4ed3c5> is a partial solution
I wrote today. The remaining problem is that you have to write
`wrap (RLS (\_ -> Sub Dict)) Mirror :: Layout a -> Layout a`
when `wrap' Mirror :: Layout a -> Layout a` would be ideal.

**Comment by lierdakil** [comment] 2016-05-02 05:59
@aavogt, thanks, but the way I see it, applying layout modifiers to `Layout a` is non-issue. Problems arise only when one needs to prove that there is an instance of `Read (Layout a)`, of which there are none. I don't think your code solves this problem (or maybe I'm just being stupid).

F.ex., try the following with your code:

```haskell
test :: Layout Window -> IO ()
test l = xmonad $ def{layoutHook = wrappedMirror l}
```

Of course, one could require an instance in type signature. But that would just postpone the problem:

```haskell
test :: (Read (Layout Window)) => Layout Window -> IO ()
test l = xmonad $ def{layoutHook = wrappedMirror l}

main' :: IO ()
main' = test $ Layout Full
```

I could thread a list of types that `Layout` *could* encapsulate, but that would require a type-level list, which would, again, require a different signature to `(>>) :: m1 a -> m2 b -> m2 b`, which essentially takes us out of monad category and into type-indexed monads. And that's something I'd prefer to avoid, for one, and there's an easier solution to the whole problem with type-indexed monads then threading a type list around.

**Comment by aavogt** [comment] 2016-05-02 08:27
@lierdakil the problem is that you have to write and maintain many functions like `wrappedMirror`. That seems to be acceptable to you, but I would rather say `modify layout Mirror` rather than having to find or define a `wrappedMirror` myself.

This is a way to write your `test` in a way that doesn't need that `Read (Layout a)` instance.

    test :: Layout Window -> IO ()
    test l = xmonad2 $ def{layoutHook = wrappedMirror l}

      where xmonad2 :: XConfig Layout -> IO ()
            xmonad2 cf@ XConfig { layoutHook = Layout l } =
                xmonad cf{ layoutHook = l }

**Comment by lierdakil** [comment] 2016-05-02 10:18
@aavogt, okay, that's me being stupid then.

While you are apparently right about `Mirror`, I found some success with generalized wrapper for `LayoutModifier` instances:

```haskell
newtype RLS' m a = RLS' (forall l. l a
                          -> (Read (l a), Read (m a), LayoutClass l a)
                          :- (Read (ModifiedLayout m l a), LayoutClass (ModifiedLayout m l) a))

wrapLM :: forall m a. (LayoutModifier m a, Read (m a))
      => (forall l. (LayoutClass l a, Read (l a)) => l a -> ModifiedLayout m l a)
      -> Layout a -> Layout a
wrapLM m (Layout la) =
  let (RLS' rS' :: RLS' m a) = RLS' $ const $ Sub Dict
  in case rS' la of
    Sub Dict -> Layout (m la)
```

which ultimately allows for syntax like this:

```haskell
main = xmonad' $ do
    modifyLayout' minimize
    modifyLayout' borderResize
    modifyLayout' smartBorders
    modifyLayout' avoidStruts
```

Alas, at this point I have no idea how to generalize this to

```haskell
main = xmonad' $ do
    modifyLayout' $ minimize . borderResize . smartBorders . avoidStruts
```

but that's at least some progress, I guess?

**Comment by lierdakil** [comment] 2016-05-02 16:03
Okay, so I fiddled around a bit, and came to a more concise implementation that relies on typeclasses (or rather, a single typeclass) to build constraint entailment. Here's a [gist](https://gist.github.com/lierdakil/77db93bd8252c2158a7090d3daa3c5f3) with a minimal example.

It boils down to a single `wrap :: (l a -> m l a) -> Layout a -> Layout a` function, and a single instance for each thing like `Mirror`:

```haskell
instance CC Mirror a where dict = Dict
```

Adding instances seems like less of a hassle. Of course it'd be better if it would derive automagically, as is the case with `LayoutModifier`s, but I found no meaningful way to do so. So if anyone has ideas, I'm eager to hear those. In the meantime, I'll see if I can make a sensible patch to Prime with this.

**Comment by aavogt** [comment] 2016-05-02 19:54
@lierdakil I like your solution. [Here](https://gist.github.com/aavogt/9951e0e7f62e1b94fecd79793c50f935) is some template haskell to find `LayoutClass` instances including those that wouldn't be covered by the `CC` instance for `LayoutModifier`. I was expecting more instances to need special treatment, and a dozen hand-written `CC` instances are probably less work than template haskell (to generate those instances).

Keep in mind that contrib has very rarely added dependencies, so I am going to follow suit and say: don't add the constraints package to the build-depends and instead copy the two data definitions you need. Contrib might still compile with ghcs that are older than `-XConstraintKinds`, so there's another question of whether the module that this code winds up in should be disabled with ghc<7.5 (or another version). But those details are secondary to having something that is well thought out and works on the configurations that travis is set up to test.

**Comment by lierdakil** [comment] 2016-05-04 16:36
So, I've run into another annoying brick wall :(

Functions like `modifyLayout` can only accept a single modifier. So something like this works:

```haskell
modifyLayout (Full |||)
modifyLayout Mirror
```

and something like this does not:

```haskell
modifyLayout $ Mirror . (Full |||)
```

The real problem is it's entirely possible to have pure (or `IO`) functions that modify layout arbitrarily. So, for example, consider a function

```haskell
stupidLayoutModifier = Mirror . (Full |||) -- yes, I know it's rather stupid, but it's an example
```

that's defined somewhere in the depths of xmonad-contrib.

User tries to use it, and typechecker explodes in his face:

```haskell
modifyLayout stupidLayoutModifier
```

```
Couldn't match type ‘l’ with ‘Choose Full l’
  ‘l’ is a rigid type variable bound by
      a type expected by the context:
        LayoutClass l Window => l Window -> Mirror l Window
Expected type: l Window -> Mirror l Window
  Actual type: l Window -> Mirror (Choose Full l) Window
```

I was able to partially work around the problem by playing with type composition operator (similar to  TypeCompose library). But workaround ends up being rather annoying, e.g. to make above example work, one needs to change it as follows:

```haskell
modifyLayout $ O . stupidLayoutModifier
```

In general, if layout modifier function applies `n` modifiers, `O` needs to be invoked `n-1` times. Which gets tedious pretty fast.

Any insight is welcome.

A toy implementation is available as [gist](https://gist.github.com/lierdakil/f2c46ad727506d5986b831b9d4c9dd89), if anyone wishes to poke at it.

**Comment by lierdakil** [comment] 2016-05-04 23:17
After some more poking, I found a partial solution. It's possible to define a number of instances like this:

```haskell
class S l f t | f l -> t where
  sq :: (l a -> f a) -> (l a -> t l a)

instance S l (m1 l) m1 where
  sq = id
instance S l (m1 (m2 l)) (m1 :. m2) where
  sq = sq . (O .)
instance S l (m1 (m2 (x l))) (m1 :. m2 :. x) where
  sq = sq . (O .)
instance S l (m1 (m2 (m3 (x l)))) (m1 :. m2 :. m3 :. x) where
  sq = sq . (O .)
instance S l (m1 (m2 (m3 (m4 (x l))))) (m1 :. m2 :. m3 :. m4 :. x) where
  sq = sq . (O .)
...
```

This seems to beg for an abstraction via recursive instance, but I can't seem to find a proper way to define one.

**Comment by aavogt** [comment] 2016-05-05 17:02
@lierdakil [I figured out how to get those two instances to cover all uses of S here](https://gist.github.com/aavogt/fe4599bfbb0b16e867cab0fdbd9a9899). I used IncoherentInstances so maybe there's still a way to avoid that unsavoury extension. On the other hand the extension seems to be doing the right thing so maybe that part is fine as-is.

**Comment by lierdakil** [comment] 2016-05-05 22:24
@aavogt *thank you*. I was at my wit's end with this. I actually half-written a TH function to generate an absurd amount of instances like ones above. And I will happily take one incoherent instance over TH any day of the week!

**Comment by lierdakil** [comment] 2016-05-07 01:12
I think I'm at the point where I can't do much more. It's still pretty awkward in places. A few examples:

- Need separate functions to execute config transformers that change layout and that do not. I don't think it's possible to work around this. Perhaps if associated type families were less strict w.r.t. overlap. As a result, `apply` and `applyIO` have two variants each.
- Need to 'squash' a stack of layout modifiers into single composed modifier. There are obviously different implementations for pure and IO functions on config and layout modifiers themselves. I couldn't figure out a way to hide this plumbing (I sincerely doubt it's possible), so it needs to be explicit. Thankfully, it's not required often.

However, I switched my config to use it, and it's not that bad. Besides, it's *much* easier to embed IO actions when `>>=` and `lift` are available in `Prime`.

Current work is available [here](https://github.com/lierdakil/xmonad-prime-monad). Not really sure if I should create a PR, due to reasons explained above. I will probably take a break from fighting with typechecker for now.

**Comment by TheMC47** [comment] 2022-03-13 15:37
Since `XMonad.Config.Prime` is deprecated (see #679), I'm gonna close this issue.

**Closed by TheMC47** 2022-03-13 15:37 UTC
