### ISSUE TITLE
High cpu usage on layered submap

### ISSUE THREAD

**Issue by BlackCapCoder** [xmonad/xmonad-contrib#262] opened 2018-06-14 00:03 UTC
```haskell
import XMonad (xmonad, def)
import XMonad.Actions.Submap (submap)
import XMonad.Util.EZConfig (mkKeymap, additionalKeysP)

foo conf = additionalKeysP conf
  [ ("a", submap $ mkKeymap conf
      [ ("b", submap $ mkKeymap conf []) ] 
    )
  ]

main = xmonad $ foo def
```

If `a` then `b` is pressed, I get 3 new threads with 100% cpu usage. I have 4 cores. These go away if anything else is pressed.

**Comment by BlackCapCoder** [comment] 2018-06-14 00:17
https://github.com/xmonad/xmonad-contrib/blob/e0b1954e621690f17d1a0056de48abf4e875e970/XMonad/Actions/Submap.hs#L74-L97

That `fix` on line 81 is probably the offending function, but I don't quite understand why

**Comment by BlackCapCoder** [comment] 2018-06-14 00:33
When typing `abc`, the fix loop is only ran twice :confused:

**Comment by BlackCapCoder** [comment] 2018-06-14 01:12
Profile: https://gist.github.com/BlackCapCoder/5633dd11ade8decd8983bcda63881ce4

**Comment by BlackCapCoder** [comment] 2018-06-14 13:11
`EZConfig` uses submap internally, so the problem can also be created like this:
```haskell
import XMonad (xmonad, def)
import XMonad.Util.EZConfig (mkKeymap)

main = xmonad $ mkKeymap def [("a b c", pure ())]
```

**Comment by BlackCapCoder** [comment] 2018-06-14 13:36
`EZConfig` uses submap internally. Interestingly, in the following example `f2` does have the problem, but `f1` does not:
```haskell
import XMonad (xmonad, def, layoutHook)
import XMonad.Util.EZConfig (additionalKeysP)
import XMonad.Layout.BinarySpacePartition (emptyBSP)

f1 = xmonad $ additionalKeysP
  def
  [ ("a b c", error "foo") ]

f2 = xmonad $ additionalKeysP
  def { layoutHook = emptyBSP }
  [ ("a b c", error "foo") ]
```

**Comment by slotThe** [comment] 2021-06-19 07:22
Due to this part

> I get 3 new threads with 100% cpu usage. I have 4 cores. 

I believe this is the same issue as #483.  I will close this, because we have figured out the cause there (still working on the reason though :))

**Closed by slotThe** 2021-06-19 07:22 UTC

**Comment by liskin** [comment] 2021-08-09 00:18
Yep, very likely the same as #483, proposed fix here: https://github.com/xmonad/X11/pull/78
