### ISSUE TITLE
Line navigation misbehaves in X.A.Navigation2D

### ISSUE THREAD

**Issue by pjones** [xmonad/xmonad-contrib#163] opened 2017-04-13 00:00 UTC
### Problem Description

Starting with commit  b9215181bb835e0203babd27613bb938ab0f270c line navigation will skip over windows on the current workspace and move to a window on another monitor.

This is easy to reproduce on layouts that have three or more columns if you have multiple monitors.  Focus a window on the far left of the workspace. Use `Navigation2D` to move to the right.  Notice that windows in the far right column will be skipped over and the focus will go to the next monitor.

Previously, if line navigation failed to find an appropriate window on the current workspace it would fall back to using center navigation.  The referenced commit above changed that behavior.

**Comment by ChristopherDavenport** [comment] 2017-04-25 17:28
I will take a shot at this one. It seems manageable.

**Comment by LSLeary** [comment] 2017-09-26 19:41
I thought my PR would close this, but I took a closer look and it's probably something else.

Re that commit, if you go back a bit you'll see it's actually me reverting my own defacement of the doLineNavigation function—I'd modified it temporarily in the early stages of testing my hybridNavigation idea. This is a great example of why you should squash commits; had I done so at the time, the combined commit would have had diff:
```shell
git diff 529683660c94d91c094166c43a56230a5fd02ee7 4358f58de8d9a84cfaa2d57e054c8c90fb04069a XMonad/Actions/Navigation2D.hs
```

You can see there is no net change to line navigation. I took a further look through the history of that file in particular, and it doesn't seem that there's any net change to doLineNavigation since its inception, so the issue probably lies in some surrounding configuration.

**Comment by LSLeary** [comment] 2018-07-02 07:03
I think this was probably just a bad (but expected) interaction between `lineNavigation` and either `X.L.Spacing` or `X.L.Decoration` (in the case of which `lineNavigation` should be replaced with `sideNavigation`); I can't actually reproduce it otherwise.

**Closed** 2021-04-10 14:43 UTC
Labels: 0.kind: bug, 2.status: work-in-progress, 4.effort: trivial, 6.topic: actions, 9.needs: reproducible via config, good first issue
