### ISSUE TITLE
Window Swallowing swallowing other windows

### ISSUE THREAD

**Issue by AMTitan** [xmonad/xmonad-contrib#790] opened 2022-12-22 00:49 UTC
### Problem Description

Just so you know this is maybe one of the most random glitches. Window swallowing can eat up other windows and move windows to other work spaces with multi monitor. When in this glitched mode your window that you had window swallowing for will move work spaces depending on where your mouse is even if its not in your config.

### Steps to Reproduce

Requirements:
- Atleast 2 monitors (only tested with 2 monitors)
- Master stack maybe required I have not checked

To make:
- open **2** terminals on one screen and open **1** terminal (can be anything) on the other screen
- in one of the two terminals make a window that will close after a few secs ex. `mpv https://www.w3schools.com/html/mov_bbb.mp4`
- move your cursor to the lonely window and focus it
- wait for the window to close now

Your two terminals now should be on the workspace that your lonely window was on and if you move your mouse to another monitor it will follow workspaces. Your lonely window is now gone but running in the background and as far as I know there is no way to get that window back.

### Configuration File

Please include the smallest _full_ configuration file that reproduces
the problem you are experiencing:

Should just be able to use the default window swallowing config but if needed.
[xmonad.hs](https://github.com/xmonad/xmonad-contrib/files/10282735/xmonad.hs.txt)

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - I tested my configuration
    - [x] With `xmonad` version 0.17.1
    - [x] With `xmonad-contrib` version 0.17.1

**Comment by slotThe** [comment] 2022-12-31 10:25
This is more or less a duplicate of #752; X.H.WindowSwallowing is _very_ hardcoded to a single monitor at this point and behaves in pretty nasty ways if this invariant is broken.  I suppose we should at least mention this in the documentation until we get a chance to rework the module.  Contributions welcome!

**Closed by slotThe** 2022-12-31 10:25 UTC
